import {
	UPDATE_PRODUCTS,
	ADD_TO_CART,
	ADD_MULTIPLE_TO_CART,
	REMOVE_FROM_CART,
	CLEAR_CART,
	UPDATE_CART_QUANTITY,
	TOGGLE_CART,
	UPDATE_CATEGORIES,
	UPDATE_CURRENT_CATEGORY,
} from "../actions/actions";
